// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", false);
user_pref("app.normandy.startupExperimentPrefs.network.cookie.cookieBehavior", 0);
user_pref("app.normandy.startupExperimentPrefs.network.http.spdy.websockets", false);
user_pref("app.normandy.user_id", "20ffe130-28a3-4cbe-adbe-3da25130f17a");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1550177694);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1550177814);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1550239444);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1550221684);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1550221564);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1550177574);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1550178054);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1550177934);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1550177185);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{c7564a2f-6a89-4161-bbc1-bda2675b5b6d}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1550169000);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1550241305882");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1550243123882");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1550239445833");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1550243045833");
user_pref("browser.search.region", "IN");
user_pref("browser.slowStartup.averageTime", 9721);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190128143901");
user_pref("browser.startup.homepage_override.mstone", "65.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1550177194844");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "a0f21594d3f64951901625af7455e1e3");
user_pref("extensions.blocklist.lastModified", "Fri, 08 Feb 2019 12:03:20 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1550177697);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190128143901");
user_pref("extensions.lastAppVersion", "65.0");
user_pref("extensions.lastPlatformVersion", "65.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{185c3b46-cc6f-47e1-bdb9-a894971a39ad}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"bc277cee-60d4-4717-b703-439ab3e2af4c\",\"screenshots@mozilla.org\":\"14a73413-fbb4-4f02-9f3a-688b3c010a4f\",\"webcompat-reporter@mozilla.org\":\"60a4d90b-73fa-437d-9eba-102cdd5df754\",\"webcompat@mozilla.org\":\"f95b5e4b-1ddb-4c02-9bba-5adc8144150c\",\"fxmonitor@mozilla.org\":\"fdfcd133-f668-46c6-bdc3-799f16717e55\"}");
user_pref("font.internaluseonly.changed", true);
user_pref("idle.lastDailyNotification", 1550222758);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.benchmark.vp9.fps", 8);
user_pref("media.benchmark.vp9.versioncheck", 5);
user_pref("media.gmp-gmpopenh264.abi", "x86-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1550177486);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190128143901");
user_pref("media.gmp-manager.lastCheck", 1550177485);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1550222759);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "3d664481-61b4-4922-8e2c-67339b42fce8");
user_pref("security.sandbox.plugin.tempDirSuffix", "0615ce57-f412-40d4-913b-1a6789b472b6");
user_pref("services.blocklist.addons.checked", 1550173329);
user_pref("services.blocklist.gfx.checked", 1550173329);
user_pref("services.blocklist.onecrl.checked", 1550173329);
user_pref("services.blocklist.pinning.checked", 1550173329);
user_pref("services.blocklist.plugins.checked", 1550173329);
user_pref("services.settings.clock_skew_seconds", -14);
user_pref("services.settings.last_update_seconds", 1550177588);
user_pref("services.settings.main.language-dictionaries.last_check", 1550173329);
user_pref("services.settings.main.onboarding.last_check", 1550173329);
user_pref("services.settings.main.sites-classification.last_check", 1550173329);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1550222758);
user_pref("toolkit.startup.last_success", 1550221409);
user_pref("toolkit.telemetry.cachedClientID", "55fd73ec-5106-4c24-aa8a-64fbf6f66a9e");
user_pref("toolkit.telemetry.previousBuildID", "20190128143901");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
